### ISSUE TITLE
Secret keys go from A to [ (or maybe from B to [)

### ISSUE THREAD

**Issue by newgrp** [petersbob/keyboard_smasher#1]
I've never seen A show up, in any case, but I've had [ multiple times.

**Comment by petersbob** [comment]
I'm having trouble recreating this. Are you hitting "[" and its making a sounds? or does it appear in the console?

**Comment by newgrp** [comment]
Console

**Comment by petersbob** [comment]
Fixed a rounding error in the change_key method. That should fix it.
